formatter: markdown table

version: "0.20.0"

sections:
  hide: []
  show:
    - requirements
    - providers
    - resources
    - inputs
    - outputs
    - modules

sort:
  enabled: true
  by: name

settings:
  anchor: false
  default: true
  description: true
  escape: true
  hide-empty: false
  html: false
  indent: true
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true
