#!/usr/bin/env python3
"""
Convert Markdown files generated by terraform-docs to RST format for Sphinx.
This script converts Markdown tables and headers to RST format.
"""

import re
import sys
from pathlib import Path


def markdown_table_to_rst(markdown_content):
    """Convert Markdown table to RST table format."""
    lines = markdown_content.split('\n')
    rst_lines = []
    in_table = False
    table_rows = []
    
    for line in lines:
        # Detect Markdown table
        if '|' in line and not line.strip().startswith('#'):
            if not in_table:
                in_table = True
                table_rows = []
            
            # Clean up the line
            cells = [cell.strip() for cell in line.split('|')]
            cells = [c for c in cells if c]  # Remove empty cells
            
            if cells:
                table_rows.append(cells)
        else:
            if in_table and table_rows:
                # Convert table to RST
                if len(table_rows) >= 2:
                    # Header row
                    header = table_rows[0]
                    separator = table_rows[1]  # Separator row
                    
                    # Determine column widths
                    col_widths = []
                    for i in range(len(header)):
                        max_width = max(
                            len(header[i]) if i < len(header) else 0,
                            max(len(row[i]) if i < len(row) else 0 for row in table_rows[2:])
                        )
                        col_widths.append(max(max_width, 3))
                    
                    # Build RST table
                    rst_lines.append('.. list-table::')
                    rst_lines.append('   :header-rows: 1')
                    rst_lines.append('   :widths: ' + ' '.join(str(w) for w in col_widths))
                    rst_lines.append('')
                    
                    # Header
                    for i, cell in enumerate(header):
                        prefix = '   * - ' if i == 0 else '     - '
                        rst_lines.append(f'{prefix}{cell}')
                    
                    # Data rows
                    for row in table_rows[2:]:
                        for i, cell in enumerate(row):
                            prefix = '   * - ' if i == 0 else '     - '
                            rst_lines.append(f'{prefix}{cell}')
                    
                    rst_lines.append('')
                
                table_rows = []
                in_table = False
            
            # Convert headers
            if line.startswith('#'):
                level = len(line) - len(line.lstrip('#'))
                header_text = line.lstrip('#').strip()
                
                if level == 1:
                    rst_lines.append(header_text)
                    rst_lines.append('=' * len(header_text))
                elif level == 2:
                    rst_lines.append(header_text)
                    rst_lines.append('-' * len(header_text))
                elif level == 3:
                    rst_lines.append(header_text)
                    rst_lines.append('~' * len(header_text))
                else:
                    rst_lines.append(header_text)
                    rst_lines.append('^' * len(header_text))
                rst_lines.append('')
            else:
                rst_lines.append(line)
    
    return '\n'.join(rst_lines)


def convert_file(md_file, rst_file):
    """Convert a Markdown file to RST."""
    with open(md_file, 'r', encoding='utf-8') as f:
        md_content = f.read()
    
    rst_content = markdown_table_to_rst(md_content)
    
    with open(rst_file, 'w', encoding='utf-8') as f:
        f.write(rst_content)
    
    print(f"Converted {md_file} -> {rst_file}")


def main():
    """Main function."""
    if len(sys.argv) < 3:
        print("Usage: markdown_to_rst.py <input.md> <output.rst>")
        sys.exit(1)
    
    md_file = Path(sys.argv[1])
    rst_file = Path(sys.argv[2])
    
    if not md_file.exists():
        print(f"Error: {md_file} does not exist")
        sys.exit(1)
    
    convert_file(md_file, rst_file)


if __name__ == '__main__':
    main()
